version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - unused

    - errorlint
    - nilerr
    - nilnesserr
    - durationcheck
    - makezero
    - unconvert
    - wastedassign
    - predeclared

    - revive
    - gocritic
    - misspell
    - wastedassign

  exclusions:
    presets:
      - comments
